# Generated by Django 2.0.5 on 2018-07-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
