# Generated by Django 2.0.5 on 2018-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')]),
        ),
    ]
